name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update production
        run: |
          cd /home/www/laravel-app
          git fetch origin
          git reset --hard origin/master

      - name: Install PHP dependencies
        run: |
          cd /home/www/laravel-app
          composer install --no-dev --optimize-autoloader

      - name: Install JS dependencies
        run: |
          cd /home/www/laravel-app
          npm ci

      - name: Build frontend
        run: |
          cd /home/www/laravel-app
          npm run build

      - name: Run migrations
        run: |
          cd /home/www/laravel-app
          php artisan migrate --force

      - name: Clear Laravel cache
        run: |
          cd /home/www/laravel-app
          php artisan optimize:clear